# frozen_string_literal: true

require "yaml"
require "securerandom"

# Generates a billing-rate "override" file for one resource kind (:vm / :postgres).
#
# The override file is the existing base file copied verbatim, followed by a
# generated section covering the full resource_type x resource_family x region
# matrix at unit_price 0 for every combination not already present in the base.
# Existing records always take precedence and are never re-emitted.
#
# UUID stability comes from read-back: an existing override id for a given
# natural key is reused, and brand-new combinations get a fresh random uuid
# (matching the helm template + manual entries). Because committed ids are read
# back on subsequent runs, output is stable and a CI check can assert that
# re-running the generator produces no diff.
class BillingRateGenerator
  GENERATED_HEADER = "# --- generated by bin/generate_billing_rates.rb; do not edit by hand ---"

  # kind: :vm / :postgres; config: the provider's billingRatesGenerator hash
  # (string keys, including "activeFrom").
  def initialize(kind:, config:, base_text:, override_text: nil)
    @kind = kind.to_sym
    @config = config
    @base_text = base_text.to_s
    @override_text = override_text
  end

  # The full matrix of records (without ids), in canonical iteration order.
  def matrix_records
    families = Array(@config["instanceResourceFamilies"])
    regions = Array(@config["regions"])
    records = []
    if @kind == :vm
      Array(@config["vmResourceTypes"]).each do |type|
        families.each { |family| regions.each { |region| records << record(type, family, region) } }
      end
    else
      Array(@config["postgresStorageTypes"]).each do |type|
        regions.each { |region| records << record(type, "standard", region) }
      end
      Array(@config["postgresVCpuTypes"]).each do |type|
        families.each { |family| regions.each { |region| records << record(type, "standard-#{family}", region) } }
      end
    end
    records
  end

  def generate
    base_key_set = parse(@base_text).map { natural_key(it) }.to_set

    override_records = parse(@override_text)
    override_id_by_key = {}
    override_records.reverse_each { |rec| override_id_by_key[natural_key(rec)] = rec["id"] }

    matrix = matrix_records
    record_by_key = matrix.to_h { [natural_key(it), it] }
    generated_keys = matrix.map { natural_key(it) }.reject { base_key_set.include?(it) }
    generated_set = generated_keys.to_set

    existing_order = override_records.map { natural_key(it) }.select { generated_set.include?(it) }.uniq
    existing_set = existing_order.to_set
    ordered_keys = existing_order + generated_keys.reject { existing_set.include?(it) }

    lines = ordered_keys.map do |key|
      rec = record_by_key[key]
      format_record(rec.merge("id" => override_id_by_key[key] || SecureRandom.uuid))
    end

    result = +""
    unless @base_text.strip.empty?
      result << @base_text
      result << "\n" unless result.end_with?("\n")
    end
    unless lines.empty?
      result << GENERATED_HEADER << "\n"
      lines.each { |line| result << line << "\n" }
    end
    result
  end

  private

  def record(type, family, region)
    {
      "resource_type" => type,
      "resource_family" => family,
      "location" => region,
      "unit_price" => 0.0,
      "billed_by" => "duration",
      "active_from" => active_from,
      "byoc" => false,
    }
  end

  def active_from
    value = @config.fetch("activeFrom")
    value.is_a?(Time) ? value.utc.strftime("%Y-%m-%dT%H:%M:%SZ") : value.to_s
  end

  def natural_key(rec)
    [rec["resource_type"], rec["resource_family"], rec["location"], rec["billed_by"], rec["byoc"]]
  end

  def parse(text)
    return [] if text.nil? || text.strip.empty?
    YAML.load(text, permitted_classes: [Time]) || []
  end

  def format_record(rec)
    format(
      "- { id: %s, resource_type: %s resource_family: %s location: %s unit_price: %.10f, billed_by: %s, active_from: %s, byoc: %s }",
      rec["id"],
      "#{rec["resource_type"]},".ljust(28),
      "#{rec["resource_family"]},".ljust(27),
      "#{rec["location"]},".ljust(15),
      rec["unit_price"].to_f,
      rec["billed_by"],
      rec["active_from"],
      rec["byoc"],
    )
  end
end
